config/routes.rb
Rails.application.routes.draw do
  root to: 'calendars#index'
  resources :calendars , only: [:show, :create], param: :date
  resources :reservations
  devise_for :users 
  resources :users do
    member do
      get :edit_name
      get :edit_password
      get :edit_email
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.role.eql? 'Admin'
      can :manage, :all
    else
      can :read, :all
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calendar.rb
class Calendar < ApplicationRecord
  has_one :reservation, dependent: :delete
  has_one :user, through: :reservation

  def self.clean_old_records
    Calendar.where('date < ?', Date.today.to_formatted_s(:db)).delete_all
  end
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :calendar
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :reservations
  has_many :calendars, through: :reservations
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  def index; end

  def show
    @date = params[:date][3..]
    @open = Tod::TimeOfDay.new 8
    @close = Tod::TimeOfDay.new 21
    @current = @open
    @day = params[:date][0..2]
  end

  def create
    @calendar = Calendar.create(calendar_params)
    @res = Reservation.create(calendar_id: @calendar.id, user_id: current_user.id)
    if @res.save && @calendar.save
      flash[:notice] = 'Reserved'
      redirect_to request.referrer
    end
  end

  private

  def calendar_params
    params.permit(:date, :start_time, :end_time, :day)
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def destroy
    @reservation = Reservation.find(params[:id])
    @calendar = Calendar.find(@reservation.calendar_id)
    @calendar.destroy
    flash[:notice] = 'Reservation Canceled'
    redirect_to request.referrer
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @reservations = current_user.reservations
    @calendars = current_user.calendars.includes([:reservation])
  end

  def edit_name; end

  def edit_password; end

  def edit_email; end

  def update; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
  def not_reserved?(date, time)
    !Calendar.where('date = ? AND start_time = ?', date, time).present?
  end

  def find(date, start_time)
    Calendar.find_by('date = ? AND start_time = ?', date, start_time)
  end

  def outdated?(date)
    Date.current.to_s >= date.to_s
  end

  def full_day
    %w[Monday Thuesday Wednesday Thursday Friday Saturday Sunday]
  end

  def day(date)
    date.inspect[0..2].to_s
  end

  def to_h(time)
    time.strftime('%H:%M')
  end

  def can_reserve?(start_time, current_date)
    !(Time.new.hour.to_s >= start_time[0..1] && Date.today.to_formatted_s(:db) >= current_date)
  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/calendars/_reserve_form.html.erb
<%if user_signed_in? %>
  <%= form_with url: calendars_path do |f| %>
    <%= f.hidden_field  :date, value: date %>
    <%= f.hidden_field  :day, value: day %>
    <%= f.hidden_field  :start_time, value: start_time%>
    <%= f.hidden_field  :end_time, value: end_time%>
    <% if can_reserve?(start_time, date) %>
      <%= f.submit "Reserve", class:'reserveButton'%>
    <% end %>
  <% end %>
<% end %>

app/views/calendars/index.html.erb
<%= week_calendar do |date| %>
  <%unless outdated? date  %>
    <%link_to calendar_path("#{day(date)}#{date}") do %>
      <%= date %>
    <%end %>
  <% else %>
    <span class="outdated">Not Available</span>
  <%end%>
<% end %>

app/views/calendars/show.html.erb
<h1 class="text-center"><%= "#{@day} #{@date}" %></h1>
<section class="d-flex flex-wrap">
  <% while @open <= @close do %>
    <%
      @start_time = @open 
      @end_time = @open+3600 
      @open_to_h =  to_h(@open)
    %> 
    <div class="d-flex flex-column w-30 bg-danger flex-wrap m-2">
      <div class="w-50 text-center p-2">
        <%="start:#{@start_time} end#{@end_time}"%>
      </div>
      <% if not_reserved? @date, @open_to_h%>
        <%= render 'reserve_form',
        date: @date, day: @day, start_time: @open_to_h,
        end_time: to_h(@end_time) %>
      <% else %>
        <%@calendar = find @date,@open_to_h%>
        <% if can? :delete, Calendar, user:current_user %>
            <div>
              <%= link_to 'Cancel reservation', reservation_path(@calendar.reservation.id),class:'btn btn-primary', method: :delete%>
            </div>
          <% end %>
        <div>   
          <%= @calendar.user.email %>
        </div>
      <% end %>
    </div>
      <%@open+= 3600%>
  <% end %>
</section>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg nav">
  <div class="container-fluid header">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav w-50 navLinks">
        <%if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'My account', current_user, class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to 'Reserve', :root, class:"nav-link"%>
        </li>
        <li class="nav-item">
            <%= link_to 'Log out', destroy_user_session_path, class:"nav-link" , method: :delete%>
        </li>

         <li class="nav-item d-flex">
          <select name="career" id="career" class="options" onchange="location = this.value;" method="GET">
            <option value="" selected hidden>Options</option>
            <option value="<%=edit_name_user_path(current_user)%>">Edit name</option>
            <option value="<%=edit_password_user_path(current_user)%>">Edit password</option>
            <option value="<%=edit_email_user_path(current_user)%>">Edit email</option>
          </select>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to 'Sign In' , new_user_session_path, class:"nav-link"%>
        </li>
 
      <% end %>
        
      </ul>

      <div class="w-50 d-flex align-content:center">
        <% if notice %>
          <p class="alert border-none p-0 m-0"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert"><%= alert %></p>
        <% end %>
      </div>
    </div>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FootballReservations</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

  <body>
    <main class="wrapper">
      <%= render 'layouts/header' %>
      <%= yield%>
    </main>
  </body>
</html>

app/views/reservations/destroy.html.erb
<h1>Reservations#destroy</h1>
<p>Find me in app/views/reservations/destroy.html.erb</p>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
                      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: '<<'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: '>>'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class='v-align-center d-flex'>
  <div class="simple-calendar w-50 margin-0-auto reserveWrapper">
    <div class="calendar-heading d-flex justify-content-center w-100 p-3">
      <%= link_to t('simple_calendar.previous', default: '<<'), calendar.url_for_previous_view , class:'changeWeek'%>
      <% if calendar.number_of_weeks == 1 %>
        <span class="px-5 week"><%= t('simple_calendar.week', default: 'Week') %></span>
      <% else %>
        <span class="week"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
      <% end %>
      <%= link_to t('simple_calendar.next', default: '>>'), calendar.url_for_next_view,class:'changeWeek' %>
    </div>

    <table class="table table-striped row justify-content-center text-center">
      <thead class="col-5">
        <tr class="row">
          <% full_day.each do |day| %>
            <th class="col-12"><%= day %></th>
          <% end %>
        </tr>
      </thead>

      <tbody class="col-5">
        <% date_range.each_slice(7) do |week| %>
          <tr class="row h-100">
            <% week.each do |day| %>
              <%= content_tag :td, class:'col-12' do %>
                <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                  <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
                <% else %>
                  <% passed_block.call day, sorted_events.fetch(day, []) %>
                <% end %>
              <% end %>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/_calendars.html.erb
<section class="d-flex flex-wrap reservedCardWrapper">
  <% @calendars.each do |c| %>
    <section class="text-center m-2 reservedCard" style="width: 50%;" >
      <div class="card-img-top">
        <p> <%= c.day %> <%= c.date%></p>
      </div>
      <div class="card-body">
      <p class="card-text">Start: <%= c.start_time %></p><p class="">End:<%= c.end_time %></p>
      </div>
      <div> <%= link_to 'Cancel reservation', reservation_path(c.reservation.id),class:'btn cancelReservation', method: :delete%> </div>
    </section>
  <% end %>
</section>

app/views/users/edit_email.html.erb
<h1>Edit your email</h1>

app/views/users/edit_name.html.erb
<h1>Edit your name</h1>

app/views/users/edit_password.html.erb
<h1>Edit your password</h1>

app/views/users/show.html.erb
<h1 class="p-5 text-center">My account</h1>
<% if @calendars%> 
  <%= render 'users/calendars'%>
<% end %>